name: Check if file exists
description: 'Check if mpc-qt wrote a file'

inputs:
  filename:
    description: 'Name of the file to check'
    required: true
    default: 'no_file'
runs:
  using: "composite"

  steps:
  - name: Check if mpc-qt wrote ${{ inputs.filename }}
    run:  |
      : Check if mpc-qt wrote ${{ inputs.filename }}
      if [[ -f ~/.config/mpc-qt/${{ inputs.filename }} ]]; then
        echo "mpc-qt wrote ${{ inputs.filename }} ✓"
      else
        echo "mpc-qt did NOT write ${{ inputs.filename }} ✗"
        exit 1
      fi
    shell: bash
