name: C/C++ CI Tests

on:
  [workflow_call]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Download mpc-qt build
      uses: actions/download-artifact@v4
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get -y install qt6-base-dev qt6-l10n-tools libqt6svg6-dev libgl-dev libmpv-dev xvfb
    - name: Start without config
      uses: ./.github/actions/linux/tests/start
    - name: Start with config
      uses: ./.github/actions/linux/tests/start_with_config
